---
output: md_document
author: "Imke Mayer"
date: 2025-04-04
linktitle: People
menu: navbar
title: People
name: People
url: "/people/"
weight: 6
---

#### People
<p align="justify">The community of people and research teams working on missing values is constantly growing but there are some researchers whose work can be considered as key contributions to the community and who provide a lot of material to different groups of interested people. Here we provide the links to their personal/group websites (in alphabetical order).</p>

<p align="justify"><i>If you think you or your research group should also figure on the list below feel free to contact us via the <a href="/contact/">Contact form</a>.</i></p>

<ul class="list-group" id="people-list">
<li class="list-group-item"> <a href="https://thomasberrett.github.io/" target="_blank">Thomas Berrett</a> (University of Warwick)</li>
<li class="list-group-item"> <a href="https://rohit-bhattacharya.com/" target="_blank">Rohit Bhattacharya</a> (Williams College)</li>
<li class="list-group-item"> <a href="http://www.mattblackwell.org" target="_blank">Matthew Blackwell</a> (Harvard University)</li>
<li class="list-group-item"> <a href="https://www.imo.universite-paris-saclay.fr/~claire.boyer/" target="_blank">Claire Boyer</a> (Université Paris-Saclay)</li>
<li class="list-group-item"> <a href="https://stefvanbuuren.name" target="_blank">Stef van Buuren</a> (University of Utrecht & Netherlands Organisation for Applied Scientific Research TNO)</li>
<li class="list-group-item"> <a href="https://www.maths.ed.ac.uk/~tcannings/About_Me.html" target="_blank">Timothy I. Cannings</a> (University of Edinburgh)</li>
<li class="list-group-item"> <a href="https://missingdata.lshtm.ac.uk/introduction-to-missing-data" target="_blank">James Carpenter & Jonathan Bartlett</a> (London School of Hygiene & Tropical Medecine)</li>
<li class="list-group-item"> <a href="https://www4.stat.ncsu.edu/~davidian/index.html" target="_blank">Marie Davidian</a> (North Carolina State University)</li>
<li class="list-group-item"> <a href="https://sites.google.com/site/pengdingpku/" target="_blank">Peng Ding</a> (UC Berkeley)</li>
<li class="list-group-item"> <a href="https://frellsen.org/" target="_blank">Jes Frellsen</a> (Technical University of Denmark)</li>
<li class="list-group-item"> <a href="https://www.mcleanhospital.org/profile/garrett-fitzmaurice" target="_blank">Garrett M. Fitzmaurice</a> (McLean Hospital)</li>
<li class="list-group-item"> <a href="http://www.stat.columbia.edu/~gelman/" target="_blank">Andrew Gelman</a> (Columbia University)</li>
<li class="list-group-item"> <a href="https://ofer-harel.uconn.edu/" target="_blank">Ofer Harel</a> (University of Connecticut)</li>
<li class="list-group-item"> <a href="https://steinhardt.nyu.edu/faculty/Jennifer_L_Hill" target="_blank">Jennifer L. Hill</a> (New York University)</li>
<li class="list-group-item"> <a href="https://husson.github.io/" target="_blank">François Husson</a> (AgroCampus Ouest)</li>
<li class="list-group-item"> <a href="https://www.fredjo.com/" target="_blank">Frederik Johanson</a> (Chalmers University of Technology)</li>
<li class="list-group-item"> <a href="https://sites.google.com/view/jaekwangkim/home" target="_blank">Jae-Kwang Kim</a> (Iowa State University & KAIST)</li>
<li class="list-group-item"> <a href="https://gking.harvard.edu" target="_blank">Gary King</a> (Harvard University)</li>
<li class="list-group-item"> <a href="https://www2.stat.duke.edu/~fl35/" target="_blank">Fan Li</a> (Duke University)</li>
<li class="list-group-item"> <a href="https://sites.google.com/a/umich.edu/rod-little/" target="_blank">Roderick J.A. Little</a> (University of Michigan)</li>
<li class="list-group-item"> <a href="https://pamattei.github.io/" target="_blank">Pierre-Alexandre Mattei</a> (INRIA)</li>
<li class="list-group-item"> <a href="https://sites.google.com/unifi.it/fabriziamealli" target="_blank">Fabrizia Mealli</a> (European University Institute)</li>
<li class="list-group-item"> <a href="https://statistics.fas.harvard.edu/people/xiao-li-meng" target="_blank">Xiao-Li Meng</a> (Harvard University)</li>
<li class="list-group-item"> <a href="http://www.karthikamohan.com" target="_blank">Karthika Mohan</a> (UC Berkeley)</li>
<li class="list-group-item"> <a href="https://www.kuleuven.be/wieiswie/en/person/u0056633" target="_blank">Geert Molenberghs</a> (<a href="https://ibiostat.be/online-resources" target="_blank">I-BioStat</a> & KU Leuven)</li>
<li class="list-group-item"> <a href="https://raziehnabi.com/" target="_blank">Razieh Nabi</a> (Emory University)</li>
<li class="list-group-item"> <a href="http://bayes.cs.ucla.edu/jp_home.html" target="_blank">Judea Pearl</a> (UCLA)</li>
<li class="list-group-item"> <a href="http://www2.stat.duke.edu/~jerry/" target="_blank">Jerry Reiter</a> (Duke University)</li>
<li class="list-group-item"> <a href="https://statistics.fas.harvard.edu/people/donald-b-rubin" target="_blank">Donald B. Rubin</a> (Tsinghua University)</li>
<li class="list-group-item"> <a href="https://faculty.washington.edu/msadinle/index.html" target="_blank">Mauricio Sadinle</a> (University of Washington)</li>
<li class="list-group-item"> <a href="https://www.statslab.cam.ac.uk/~rjs57/" target="_blank">Richard J. Samworth</a> (University of Cambridge)</li>
<li class="list-group-item"> <a href="https://erwanscornet.github.io/" target="_blank">Erwan Scornet</a> (Sorbonne Université)</li>
<li class="list-group-item"> <a href="https://www.mrc-bsu.cam.ac.uk/people/in-alphabetical-order/n-to-s/shaun-seaman/" target="_blank">Shaun Seaman</a> (University of Cambridge)</li>
<li class="list-group-item"> <a href="https://engineering.jhu.edu/faculty/ilya-shpitser/" target="_blank">Ilya Shpitser</a> (Johns Hopkins University)</li>
<li class="list-group-item"> <a href="https://statistics.wharton.upenn.edu/profile/ett/" target="_blank">Eric J. Tchetgen Tchetgen</a> (University of Pennsylvania)</li>
<li class="list-group-item"> <a href="https://people.orie.cornell.edu/mru8/" target="_blank">Madeleine Udell</a> (Stanford University)</li>
<li class="list-group-item"> <a href="https://gbiomed.kuleuven.be/biostat/geertverbeke" target="_blank">Geert Verbeke</a> (<a href="https://ibiostat.be/online-resources" target="_blank">I-BioStat</a> & KU Leuven)</li>
<li class="list-group-item"> <a href="https://personal.lse.ac.uk/wangt60/" target="_blank">Tengyao Wang</a> (London School of Economics and Political Science)</li>
<li class="list-group-item"> <a href="https://fisher.stats.uwo.ca/faculty/yyi/" target="_blank">Grace Y. Yi</a> (University of Western Ontario)</li>
<li class="list-group-item"> <a href="https://biostat.wiscweb.wisc.edu/staff/zhao-jiwei/" target="_blank">Jiwei Zhao</a> (University of Wisconsin–Madison)</li>
</ul>



</br>

#### Main contributors to this platform

<p align="justify">The main contributors of this platform are: <a href="http://juliejosse.com" target="_blank">Julie Josse</a>, <a href="http://www.imkemayer.com" target="_blank">Imke Mayer</a>, <a href="https://www.researchgate.net/profile/Steffen_Moritz2" target="_blank">Steffen Moritz</a>, <a href="https://audesportisse.github.io" target="_blank">Aude Sportisse</a>, <a href="https://www.njtierney.com" target="_blank">Nicholas Tierney</a> and <a href="http://www.nathalievialaneix.eu" target="_blank">Nathalie Vialaneix</a>.
</p>


<style type="text/css">
#people-list
{
	padding: 0px;
}
</style>
